source 'https://rubygems.org'
gem 'rake'
gem 'gherkin'
gem 'cucumber'
gem 'capybara'
gem 'page-object'
gem 'selenium'
gem 'selenium-client'
gem 'selenium-webdriver', '~> 2.53.4'
gem 'pry'
gem 'rb-readline'
gem 'rspec-expectations'
gem 'rspec'